name: room_movie
description: Merubah room movie native ke flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  permission_handler: ^10.0.0
  http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.11
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.4.3+7
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get: ^4.6.5

  package_info_plus: ^3.0.2
  connectivity_plus: ^3.0.2
  device_info_plus: ^8.0.0
  qr_code_scanner: ^1.0.1
  page_transition: ^2.0.9
  flutter_portal: ^1.1.2
  easy_refresh: ^3.0.4+4
  flutter_svg: ^1.1.5
  enum_to_string: ^2.0.1
  shimmer: ^2.0.0
  iconly: ^1.0.1
  badges: ^2.0.3
  fimber: ^0.6.6
  sizer: ^2.0.15
  dio: ^4.0.6
  chips_choice: ^3.0.0
  url_launcher: ^6.1.7
  android_intent_plus: ^3.1.5

  flutter_staggered_animations: ^1.1.1
  animated_splash_screen: ^1.3.0
  simple_animations: ^5.0.0+3
  flutter_staggered_grid_view: ^0.4.0
  photo_view: ^0.14.0
  transparent_image: ^2.0.0
  loading_gifs: ^0.3.0
  flutter_keyboard_visibility: ^5.4.0
  keyboard_visibility_pro: ^0.0.1
  dropdown_button2: ^1.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.2.1
  flutter_gen_runner: ^4.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/background.jpg"
  min_sdk_android: 21

# ASSETS GENERATOR
flutter_gen:
  output: lib/gen_theme/
  assets:
    package_parameter_enabled: true

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml
      - assets/color/material_design_color.xml

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:
    - family: palatino_linotype
      fonts:
        - asset: assets/font/palatino_linotype.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/html/
    - assets/html/dark/
    - assets/html/light/
    - assets/json/
    - assets/svg/
